name: Feature request
description: Suggest an improvement for the theme
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line feature request
      placeholder: "Example: Improve diff colors for light variant"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Explain your suggested change
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional
